mavenCentralPublishing=true
mavenCentralAutomaticPublishing=true
signAllPublications=true

GROUP=io.github.jakala-germany
POM_ARTIFACT_ID=transitive-dependency-check-gradle-plugin
VERSION_NAME=1.0.0

POM_NAME=Transitive Dependency Check Gradle plugin
POM_DESCRIPTION=Gradle plugin to detect and fail on overridden transitive dependency versions
POM_INCEPTION_YEAR=2025
POM_URL=https://github.com/jakala-germany/gradle-transitive-dependency-check

POM_LICENCE_NAME=Apache-2.0
POM_LICENCE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENCE_DIST=repo

POM_SCM_URL=https://github.com/jakala-germany/gradle-transitive-dependency-check
POM_SCM_CONNECTION=scm:git:git://github.com/jakala-germany/gradle-transitive-dependency-check.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/jakala-germany/gradle-transitive-dependency-check.git

POM_DEVELOPER_ID=Jakala Germany
POM_DEVELOPER_NAME=Jakala Germany
POM_DEVELOPER_URL=https://github.com/jakala-germany/
